# Generated by Django 5.1.1 on 2024-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('HND I First Semester', 'HND I First Semester'), ('HND I Second Semester', 'HND I Second Semester')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('COM 311: OPERATING SYSTEM I', 'OPERATING SYSTEM I'), ('COM 312: DATABASE DESIGN I', 'DATABASE DESIGN I'), ('COM 313: COMPUTER PROGRAMMING USING C++', 'COMPUTER PROGRAMMING USING C++'), ('COM 314: COMPUTER ARCHITECTURE', 'COMPUTER ARCHITECTURE'), ('COM 315: PYTHON PROGRAMMING LANGUAGE', 'PYTHON PROGRAMMING LANGUAGE'), ('STA 311: STATISTICAL THEORY', 'STATISTICAL THEORY'), ('STA 314: OPERATION RESEARCH I', 'OPERATION RESEARCH I'), ('GNS 301: USE OF ENGLISH III', 'USE OF ENGLISH III'), ('COM 321: OPERATING SYSTEM II', 'OPERATING SYSTEM II'), ('COM 322: DATABASE DESIGN II', 'DATABASE DESIGN II'), ('COM 323: ASSEMBLY LANGUAGE', 'ASSEMBLY LANGUAGE'), ('COM 324: INTRODUCTION', 'INTRODUCTION')], max_length=100),
        ),
    ]
