# Generated by Django 5.1.1 on 2024-10-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_semester_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
